version=1.0.0
org.gradle.daemon=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx5g "-XX:MaxMetaspaceSize=3840m" "-XX:+HeapDumpOnOutOfMemoryError" "-Dfile.encoding=UTF-8"
kotlin.code.style=official
kotlin.incremental.wasm=true
kotlin.native.ignoreDisabledTargets=true
kotlin.native.enableKlibsCrossCompilation=true
